### ISSUE TITLE
In newsletter after filling email the submi button is not working.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#10]
**Actual result:**
In newsletter after filling email the submit button is not working.
![image](https://user-images.githubusercontent.com/102131636/168970278-ee79f795-4dd6-4201-b3d1-d9be073d6b40.png)

**Expected result:**
the submit button have to be working.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  fixed please check
