### ISSUE TITLE
The shipping policy page content is missing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#12]
**Actual result:**
The shipping policy page content is missing.
The url: https://xzxcosmetics.com/pages/shipping-policy
![image](https://user-images.githubusercontent.com/102131636/168971462-802afa72-bc50-4847-9514-69e94e583d37.png)

**Expected result:**
The content have to be added.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  fixed please check .

**Comment by sudhanshu0603** [comment]
ok, resolved
