### ISSUE TITLE
When we will click on the Explore button then page is opening with 404 error.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#16]
**Actual result:**
When we will click on the Explore button then page is opening with 404 error.
![image](https://user-images.githubusercontent.com/102131636/168974440-0132c585-4e12-471d-b591-fd8d7c1cca3e.png)
![image](https://user-images.githubusercontent.com/102131636/168974409-b7bf1acd-d5ca-42df-93ca-32bded08bbfb.png)

**Expected result:**
There should not be any broken links.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  issue fixed. please check.

**Comment by sudhanshu0603** [comment]
ok, resolved
