### ISSUE TITLE
In collection page many images are missing for the collections.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#20]
**The url:**
https://xzxcosmetics.com/collections/
**Actual result:**
In collection page many images are missing for the collections.
![image](https://user-images.githubusercontent.com/102131636/168979291-14f71099-dfe9-43a9-ac30-e483cd534f75.png)

**Expected result:**
The images have to be added.

**Comment by devAlokTripathi** [comment]
client will upload

**Comment by sudhanshu0603** [comment]
ok, resolved
