### ISSUE TITLE
The count have to increase on the cart icon on the header.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#23]
**Actual result:**
The count have to increase on the cart icon on the header.
![image](https://user-images.githubusercontent.com/102131636/168983650-7c4b7f45-d0bc-4ce8-8f58-0ceb61621379.png)

**Expected result:**
the count have to increase on the header cart icon when we add products to the cart.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  issue fixed.
![image](https://user-images.githubusercontent.com/100207984/170590949-81a3a4ad-4631-4195-85bf-ac691bc20e84.png)

**Comment by sudhanshu0603** [comment]
ok, resolved
