### ISSUE TITLE
The audio is not coming for the youtube video 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#26]
**The url:**
https://xzxcosmetics.com/pages/xzx-skin
**Actual result:**
The audio is not coming for the youtube video 
![image](https://user-images.githubusercontent.com/102131636/168987442-a90e54e7-b77c-4398-ba38-7fd08f78a53b.png)

**Expected result:**
The audio have to play for the youtube video .

**Comment by devAlokTripathi** [comment]
@sudhanshu0603 not reqiured

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  not required.

**Comment by sudhanshu0603** [comment]
ok, resolved
