### ISSUE TITLE
When we click on the hambergur then then dot is coming for the wishlist added product.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#30]
**Actual result:**
When we click on the hambergur then then dot is coming for the wishlist added product.
![image](https://user-images.githubusercontent.com/102131636/168996129-48e7f3c4-8a8c-4fea-acea-ee86c3511c35.png)

**Expected result:**
The count of the added product in the wishlist have to come it will b much better.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603 issue fixed please check .

**Comment by sudhanshu0603** [comment]
ok, resolved
