### ISSUE TITLE
In cart page, the wishlist icon is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#33]
**Actual result:**
In cart page, the wishlist icon is coming.
![image](https://user-images.githubusercontent.com/102131636/169002204-041d1612-aa32-4c96-8dc4-deb81a0c2d67.png)

**Expected result:**
The wishlist should not come on the cart page.

**Comment by ui-nitinrai** [comment]
Video please

**Comment by sudhanshu0603** [comment]
resolved
