### ISSUE TITLE
When we click on the zoom + symbol on product page then the image have to be scrolling left and right but the image is fixed.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#34]
**Actual result:**
When we click on the zoom + symbol on product page then the image have to be scrolling left and right but the image is fixed.
![image](https://user-images.githubusercontent.com/102131636/169003115-a858909d-9389-44a9-8db8-63dd9fce6780.png)
![image](https://user-images.githubusercontent.com/102131636/169003160-20566c92-ddc1-44bf-abda-ecd25d126afa.png)

**Expected result:**
When we click on the zoom symbol then the fixed should not be fixed, it must be scrolling left and right then the full product images will be visible properly in mobile

**Comment by ui-nitinrai** [comment]
user can drag image after zoom

**Comment by sudhanshu0603** [comment]
ok, resolved
