### ISSUE TITLE
The links of privacy policy and terms and conditions opening different page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#35]
**Actual result:**
The links of privacy policy and terms and conditions opening different page.
![image](https://user-images.githubusercontent.com/102131636/169004772-06570e27-70ef-48b8-a4ee-057d64e97e27.png)

**Expected result:**
When we click on the links then then the it should opening the page related to it.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  issue fixed please chech.

**Comment by sudhanshu0603** [comment]
ok, resolved
