### ISSUE TITLE
For the collection page, the filters are missing 

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#36]
**The url:**
https://xzxcosmetics.com/collections/cleansers
**Actual result:**
For the collection page, the filters are missing 
![image](https://user-images.githubusercontent.com/102131636/169005985-85ede71a-1d41-401c-9252-6c0d342e2f83.png)

**Expected result:**
We can add the filter in collection page.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603 
![image](https://user-images.githubusercontent.com/100207984/170545268-afd148e2-a737-437e-923a-458863c2fcd3.png)
issue fixed.please check

**Comment by sudhanshu0603** [comment]
ok, resolved
