### ISSUE TITLE
After  successfull login, when we open the account page then the logout button is missing.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#37]
**Actual result:**
After  successfull login, when we open the account page then the logout button is missing.
![image](https://user-images.githubusercontent.com/102131636/169008130-0ef276d3-ae95-4032-b906-e7f1a3d53e13.png)

**Expected result:**
The logout button is missing in the account page.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603 issue fixed. please check

**Comment by sudhanshu0603** [comment]
ok, resolved
