### ISSUE TITLE
The wishlist button is not coming for the collection page  of the products.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#40]
**the url:**
https://xzxcosmetics.com/
https://xzxcosmetics.com/collections/cosmetics
**Actual result:** 
The wishlist button is not coming for the collection page  of the products.
![image](https://user-images.githubusercontent.com/102131636/169017869-3a955317-c2e0-46c2-97f4-133cbd58edc4.png)
![image](https://user-images.githubusercontent.com/102131636/169017924-53e1dc20-414b-43f4-bf6d-e291b2ed21d5.png)

**Expected result:**
the wishlist icon have to be visible for all the products in ipad view.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603 
![image](https://user-images.githubusercontent.com/100207984/170533419-77600fc2-4412-47b8-9f39-ae518c7e5ce1.png)

**Comment by sudhanshu0603** [comment]
Pls review, in tab/ ipad view

**Comment by ui-nitinrai** [comment]
fixed ..removed for tab and desktop

**Comment by sudhanshu0603** [comment]
ok, resolved
