### ISSUE TITLE
The banner image is breaking in ipad view

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#43]
**The url:**
https://xzxcosmetics.com/pages/xzx-skin
**Actual result:**
The banner image is breaking in ipad view(ipad mini  )
![image](https://user-images.githubusercontent.com/102131636/169028706-2f4d7592-f382-454b-805c-9dc96a36ea84.png)

**Expected result:**
The banner image should not be cropped.

**Comment by ui-nitinrai** [comment]
Section replaced.

**Comment by sudhanshu0603** [comment]
ok
