### ISSUE TITLE
The home page banners are reflected.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#45]
**Actual result:**
The home page banners are reflected.
![image](https://user-images.githubusercontent.com/102131636/169206828-9ba56225-7697-4bb4-9dae-95afb9a89bf8.png)
**The video issue:**
https://www.awesomescreenshot.com/video/8979970?key=8edf93fcc3f1eb527b09ba80e803ba25
**Expected result:**
The banners are overlapping .

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  issue fixed.

**Comment by sudhanshu0603** [comment]
ok, resolved
