### ISSUE TITLE
When we change the filter option, then the wishlist is not coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#48]
**Actual result:**
When we change the filter option, then the wishlist is not coming when we hover over the products
![image](https://user-images.githubusercontent.com/102131636/170931773-88d2132b-7e66-4728-a182-0470b03033f7.png)

**Expected result:**
The wishlist icon must be after using the filter option.

**Comment by devAlokTripathi** [comment]
![Uploading image.png…]()
fixed @sudhanshu0603
