### ISSUE TITLE
The filters are missing on the search page when we are searching the product.(eyes )

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#8]
**Actual result:**
The filters are missing on the search page when we are searching the product.(eyes )
![image](https://user-images.githubusercontent.com/102131636/168968287-c56fd249-3b4c-485e-ad4f-fa063d1e0476.png)

**Expected result:**
The filter we can use for the search page.

**Comment by devAlokTripathi** [comment]
@sudhanshu0603 
![image](https://user-images.githubusercontent.com/100207984/170834295-de98a92a-8785-4a3d-98fd-8117d7454767.png)
fixed please check

**Comment by sudhanshu0603** [comment]
ok, resolved

**Comment by sudhanshu0603** [comment]
For the filers the text is of white colour pls look into it. @ui-nitinrai 
The filter is added.
![image](https://user-images.githubusercontent.com/102131636/170921370-a76ed296-8211-439e-b82c-59890bf32fdc.png)

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please  check fixed.
![image](https://user-images.githubusercontent.com/100207984/171034746-4f1133ce-c125-465e-a674-44598c0afc81.png)
