### ISSUE TITLE
The wishlist button is missing in the store but we have given the wishlist on product when we hover on products.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Zeph-Feher-Internal---May-31st-#9]
**Actual result:**
The wishlist button is missing in the store but we have given the wishlist on product when we hover on products.
**The video issue:**
https://www.awesomescreenshot.com/video/8960258?key=c7bc4b7ce4424b573a07a095020e2c70
**Expected result:**
The wishlist is missing we can add the wishlist because we have given wishlist button on product pages and products when we hover over it .

**Comment by devAlokTripathi** [comment]
@sudhanshu0603  please check wishlist added in thew store and display in the header and card grid.

**Comment by sudhanshu0603** [comment]
Pls attach a screenshot.

**Comment by sudhanshu0603** [comment]
as discussed, wishlist not need in the desktop
